### ISSUE TITLE
OAuth token not found. Make sure to have 'Allow Scripts to Access OAuth Token' enabled in the build definition.

### ISSUE THREAD

**Issue by yangsenss** [lean-soft/pull-request-diff-copy#6]
OAuth token not found. Make sure to have 'Allow Scripts to Access OAuth Token' enabled in the build definition.

**Comment by ups216** [comment]
The latest version should run without OAuth, are you running the latest version? Can you post your build log please? Thanks

**Comment by yangsenss** [comment]
您好，这个插件有没有具体点的文档呢？我还在摸索到底怎么用....还没完全整明白

**Comment by ups216** [comment]
你需要首先给主分支（比如：master）启用分支策略(branch policy)，在里面配置 build policy 来触发一个 build，在这个build里面添加这个插件就可以根据当前的 Pull Request 的源分支(feature branch)和目标分支（一般为master）的差异生成出一个diff文件夹，里面就是这次Pull Request中所包含的改动内容。

文档我们在完善。
